# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/user/Desktop/lab_3/lab_3.srcs/sources_1/bd/zynq_keypad_system/ip/zynq_keypad_system_processing_system7_0_0/zynq_keypad_system_processing_system7_0_0.xci
# IP: The module: 'zynq_keypad_system_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/user/Desktop/lab_3/lab_3.gen/sources_1/bd/zynq_keypad_system/ip/zynq_keypad_system_processing_system7_0_0/zynq_keypad_system_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_keypad_system_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/user/Desktop/lab_3/lab_3.srcs/sources_1/bd/zynq_keypad_system/ip/zynq_keypad_system_processing_system7_0_0/zynq_keypad_system_processing_system7_0_0.xci
# IP: The module: 'zynq_keypad_system_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/user/Desktop/lab_3/lab_3.gen/sources_1/bd/zynq_keypad_system/ip/zynq_keypad_system_processing_system7_0_0/zynq_keypad_system_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_keypad_system_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
