# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/user/Downloads/sources/zybo/adventures_with_ip_integrator/constraints/adventures_with_ip.xdc

# Block Designs: bd/ip_design/ip_design.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ip_design || ORIG_REF_NAME==ip_design} -quiet] -quiet

# IP: bd/ip_design/ip/ip_design_xbar_0/ip_design_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ip_design_xbar_0 || ORIG_REF_NAME==ip_design_xbar_0} -quiet] -quiet

# IP: bd/ip_design/ip/ip_design_ps7_0_axi_periph_1/ip_design_ps7_0_axi_periph_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ip_design_ps7_0_axi_periph_1 || ORIG_REF_NAME==ip_design_ps7_0_axi_periph_1} -quiet] -quiet

# IP: bd/ip_design/ip/ip_design_nco_0_0/ip_design_nco_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ip_design_nco_0_0 || ORIG_REF_NAME==ip_design_nco_0_0} -quiet] -quiet

# IP: bd/ip_design/ip/ip_design_processing_system7_0_0/ip_design_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ip_design_processing_system7_0_0 || ORIG_REF_NAME==ip_design_processing_system7_0_0} -quiet] -quiet

# IP: bd/ip_design/ip/ip_design_zybo_audio_ctrl_0_0/ip_design_zybo_audio_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ip_design_zybo_audio_ctrl_0_0 || ORIG_REF_NAME==ip_design_zybo_audio_ctrl_0_0} -quiet] -quiet

# IP: bd/ip_design/ip/ip_design_lms_pcore_0_0/ip_design_lms_pcore_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ip_design_lms_pcore_0_0 || ORIG_REF_NAME==ip_design_lms_pcore_0_0} -quiet] -quiet

# IP: bd/ip_design/ip/ip_design_axi_gpio_1_0/ip_design_axi_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ip_design_axi_gpio_1_0 || ORIG_REF_NAME==ip_design_axi_gpio_1_0} -quiet] -quiet

# IP: bd/ip_design/ip/ip_design_axi_gpio_0_0/ip_design_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ip_design_axi_gpio_0_0 || ORIG_REF_NAME==ip_design_axi_gpio_0_0} -quiet] -quiet

# IP: bd/ip_design/ip/ip_design_led_controller_0_0/ip_design_led_controller_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ip_design_led_controller_0_0 || ORIG_REF_NAME==ip_design_led_controller_0_0} -quiet] -quiet

# IP: bd/ip_design/ip/ip_design_rst_ps7_0_100M_1/ip_design_rst_ps7_0_100M_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ip_design_rst_ps7_0_100M_1 || ORIG_REF_NAME==ip_design_rst_ps7_0_100M_1} -quiet] -quiet

# IP: bd/ip_design/ip/ip_design_auto_pc_0/ip_design_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ip_design_auto_pc_0 || ORIG_REF_NAME==ip_design_auto_pc_0} -quiet] -quiet

# XDC: /home/user/Desktop/lab_4/lab_4.gen/sources_1/bd/ip_design/ip_design_ooc.xdc
