# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Downloads/virtual_inputs.xdc

# Block Designs: bd/PmodIPs/PmodIPs.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodIPs || ORIG_REF_NAME==PmodIPs} -quiet] -quiet

# IP: bd/PmodIPs/ip/PmodIPs_processing_system7_0_0/PmodIPs_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodIPs_processing_system7_0_0 || ORIG_REF_NAME==PmodIPs_processing_system7_0_0} -quiet] -quiet

# IP: bd/PmodIPs/ip/PmodIPs_xlconcat_0_0/PmodIPs_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodIPs_xlconcat_0_0 || ORIG_REF_NAME==PmodIPs_xlconcat_0_0} -quiet] -quiet

# IP: bd/PmodIPs/ip/PmodIPs_axi_gpio_0_0/PmodIPs_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodIPs_axi_gpio_0_0 || ORIG_REF_NAME==PmodIPs_axi_gpio_0_0} -quiet] -quiet

# IP: bd/PmodIPs/ip/PmodIPs_axi_gpio_0_2/PmodIPs_axi_gpio_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodIPs_axi_gpio_0_2 || ORIG_REF_NAME==PmodIPs_axi_gpio_0_2} -quiet] -quiet

# IP: bd/PmodIPs/ip/PmodIPs_xbar_0/PmodIPs_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodIPs_xbar_0 || ORIG_REF_NAME==PmodIPs_xbar_0} -quiet] -quiet

# IP: bd/PmodIPs/ip/PmodIPs_auto_pc_0/PmodIPs_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodIPs_auto_pc_0 || ORIG_REF_NAME==PmodIPs_auto_pc_0} -quiet] -quiet

# IP: bd/PmodIPs/ip/PmodIPs_ps7_0_axi_periph_0/PmodIPs_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodIPs_ps7_0_axi_periph_0 || ORIG_REF_NAME==PmodIPs_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/PmodIPs/ip/PmodIPs_rst_ps7_0_100M_0/PmodIPs_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodIPs_rst_ps7_0_100M_0 || ORIG_REF_NAME==PmodIPs_rst_ps7_0_100M_0} -quiet] -quiet

# XDC: /home/user/Desktop/lab_0/lab_0.gen/sources_1/bd/PmodIPs/PmodIPs_ooc.xdc
