# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/zynq_keypad_system/zynq_keypad_system.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_keypad_system || ORIG_REF_NAME==zynq_keypad_system} -quiet] -quiet

# IP: bd/zynq_keypad_system/ip/zynq_keypad_system_processing_system7_0_0/zynq_keypad_system_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_keypad_system_processing_system7_0_0 || ORIG_REF_NAME==zynq_keypad_system_processing_system7_0_0} -quiet] -quiet

# IP: bd/zynq_keypad_system/ip/zynq_keypad_system_PmodKYPD_0_0/zynq_keypad_system_PmodKYPD_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_keypad_system_PmodKYPD_0_0 || ORIG_REF_NAME==zynq_keypad_system_PmodKYPD_0_0} -quiet] -quiet

# IP: bd/zynq_keypad_system/ip/zynq_keypad_system_ps7_0_axi_periph_0/zynq_keypad_system_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_keypad_system_ps7_0_axi_periph_0 || ORIG_REF_NAME==zynq_keypad_system_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/zynq_keypad_system/ip/zynq_keypad_system_rst_ps7_0_100M_0/zynq_keypad_system_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_keypad_system_rst_ps7_0_100M_0 || ORIG_REF_NAME==zynq_keypad_system_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/zynq_keypad_system/ip/zynq_keypad_system_auto_pc_0/zynq_keypad_system_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_keypad_system_auto_pc_0 || ORIG_REF_NAME==zynq_keypad_system_auto_pc_0} -quiet] -quiet

# XDC: /home/user/Desktop/lab_3/lab_3.gen/sources_1/bd/zynq_keypad_system/zynq_keypad_system_ooc.xdc
