
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2021.1
* DO NOT EDIT.
*
* Copyright (C) 2010-2026 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xnco.h"

/*
* The configuration table for devices
*/

XNco_Config XNco_ConfigTable[XPAR_XNCO_NUM_INSTANCES] =
{
	{
		XPAR_NCO_0_DEVICE_ID,
		XPAR_NCO_0_S_AXI_AXILITES_BASEADDR
	}
};


