# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/user/Desktop/lab_0/lab_0.srcs/sources_1/bd/PmodIPs/ip/PmodIPs_axi_gpio_0_0/PmodIPs_axi_gpio_0_0.xci
# IP: The module: 'PmodIPs_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/user/Desktop/lab_0/lab_0.gen/sources_1/bd/PmodIPs/ip/PmodIPs_axi_gpio_0_0/PmodIPs_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'PmodIPs_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/user/Desktop/lab_0/lab_0.gen/sources_1/bd/PmodIPs/ip/PmodIPs_axi_gpio_0_0/PmodIPs_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'PmodIPs_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/user/Desktop/lab_0/lab_0.gen/sources_1/bd/PmodIPs/ip/PmodIPs_axi_gpio_0_0/PmodIPs_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'PmodIPs_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/user/Desktop/lab_0/lab_0.srcs/sources_1/bd/PmodIPs/ip/PmodIPs_axi_gpio_0_0/PmodIPs_axi_gpio_0_0.xci
# IP: The module: 'PmodIPs_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/user/Desktop/lab_0/lab_0.gen/sources_1/bd/PmodIPs/ip/PmodIPs_axi_gpio_0_0/PmodIPs_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'PmodIPs_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/user/Desktop/lab_0/lab_0.gen/sources_1/bd/PmodIPs/ip/PmodIPs_axi_gpio_0_0/PmodIPs_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'PmodIPs_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/user/Desktop/lab_0/lab_0.gen/sources_1/bd/PmodIPs/ip/PmodIPs_axi_gpio_0_0/PmodIPs_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'PmodIPs_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
